### ISSUE TITLE
Brackets [ ] in file names not work

### ISSUE THREAD

**Issue by JechtShinryaku** [kalafut/py-imohash#13]
I have several filenames that include [ ] and when I run imosum it doesn't give an error but it doesn't return anything either.

**Comment by kalafut** [comment]
I do see an issue with the `imosum` function and shell expansion. What command are you running?

**Comment by JechtShinryaku** [comment]
From linux I tried:

`imosum filewith\[brackets\].txt`

or

`imosum filewith[brackets].txt`

but it returns nothing

**Comment by kalafut** [comment]
Thanks. I know what's going on but need to double check that the fix I'm thinking of doesn't break things in other ways.

**Comment by JechtShinryaku** [comment]
Ok, thanks for your quick response

**Comment by kalafut** [comment]
I pushed a new version that should address this. The issue was that `imosum` was globbing filenames, but they're already expanded by the shell so this was: a) unnecessary  b) caused issues if special characters were present.

**Comment by JechtShinryaku** [comment]
How fast, now it works perfectly with all my files.

Thank you very much for your work.
