### ISSUE TITLE
Accounting for media metadata?

### ISSUE THREAD

**Issue by jabberjabberjabber** [kalafut/py-imohash#17]
Thanks for putting up your implementation, it looks really useful.

I do have one piece of input:

Images, videos, and other media files contain metadata which can be changed without modifying the media itself.

For instance one could add a keyword to an image, or change the title of a video and that would create a distinctly different file if compared to the original file naively.

Unless it is desirable to count two media files as different when the media content is identical then I think it might be useful to consider this.

**Comment by kalafut** [comment]
Hi. At least in my case, I'd want to consider those as different files.

It would be possible to create what you're talking about atop the library by considering the hashed content to be just those bytes  outside the metadata. Of course, the hard part is supporting all of the types of metadata placement.

**Comment by jabberjabberjabber** [comment]
> It would be possible to create what you're talking about atop the library by considering the hashed content to be just those bytes outside the metadata. 

In my case I working on a solution for long term data hoarders with no organizational skills who bigger drives every few years and, copy or clone a new backup into one of them, and put the onus on the future them to deal with it. 

I am doing it in pieces -- the first, which is complete, is a a script which crawls through directories and finds image files and prompts a local vision capable AI to come up with keywords for them which then get placed in the metadata.

The current part is a 'singulator' which is a made up word for 'create a directory tree from an arbitrary number of other directory trees, with inconsistent structures, and assemble a single master tree with at least one copy of every file that exists in any of the other trees'. It is what a deduplicator should be, in my opinion, but I haven't been able to find anyone who done such a thing, 

Anyway, I came across your repo looking for fast hashing methods for lots of big files and it looks great. It would be perfect except for the metadata issue which is crucial for me, but it seems this is pretty commonly ignored, so I guess I just have to accept that I probably doing something wrong in my approach. I guess I will find out. 

> Of course, the hard part is supporting all of the types of metadata placement.

That's the rub, isn't it. I wonder if it the best solution is to just strip the metadata from the file and put it into a buffer with exiftool or ffmpeg instead of figuring out how to restrict to only read the media portions for every type of media container.

**Comment by kalafut** [comment]
Let me challenge you on it. Why would changing metadata *not* count as a new file and all the backup, sync whatever that follows? I've found that I can labor for a long time to fix up labels, correct dates and coordinates, etc., and if I'm doing backups I would want to that to be part of the backup, even it is in fact a few bytes in a 2GB file (though rsync can do OK in that case).

I don't know the details of your process, but maybe if you're auto-generating or having to regularly change a bunch of metadata as part of a pipeline (v.s. me manually futzing with a photo), that metadata should be keep separate, but associated with the imohash value. Like an SQLite db with all the tags, titles, etc. you want referenced to an imohash. You could optionally elect to bake that data into the real EXIF (or whatever), which would trigger a sync/backup but maybe you do it just once at the end. Again, not familiar enough with the flow to say.

**Comment by jabberjabberjabber** [comment]
> Let me challenge you on it. Why would changing metadata _not_ count as a new file and all the backup, sync whatever that follows? I've found that I can labor for a long time to fix up labels, correct dates and coordinates, etc., and if I'm doing backups I would want to that to be part of the backup, even it is in fact a few bytes in a 2GB file (though rsync can do OK in that case).

Ah, I guess I didn't explain the details.

Checking the hash for duplicates is only one step in the process. Another step will be checking for the existence of certain metadata fields. I haven't determine the exact process yet, but it will probably use a combination of which metadata fields have been filled, and with what, file modification date, and a large amount of 'default to make duplicate copies if unsure' to deal with this.

Also, I am about 75% leaning towards not bothering with skipping the metadata in videos, since the complexity of the container formats combined with the ease of screwing something up and the fact that 'duplicates' of films are sometimes desired (different edits, features, etc), would lead to a million edge cases or just generally unwanted results.

Also, I think I am going to use perceptual hashing for images to completely avoid this issue entirely. They aren't big enough to warrant sampling for the hashes, and the fingerprinting process is fairly quick anyway. 

Thanks for your input!
