### ISSUE TITLE
has plan for other hash functions except mmh3

### ISSUE THREAD

**Issue by kalafut** [kalafut/py-imohash#4]
@sharego Copied from:  https://github.com/kalafut/imohash/issues/5

this library is very usefully, but today i install on a window laptop failed. Python compile mmh3 error, so will support other hash functions?

**Comment by kalafut** [comment]
No plans to use different hash functions unless it’s found that mmh3 has some major problem. For simplicity I want an imohash to be the same across platforms and without any parameterization. 

That said, there is no reason this shouldn’t work on Windows, and if the chosen mmh3 library has issues I’d like to find one that works better cross platform.

**Comment by kalafut** [comment]
I noticed that mmh3 had an update a while back to fix a Windows issue. I've updated imohash to require this newer mmh3. Can you try it out? I don't have easy access to Windows.

**Comment by sharego** [comment]
Thanks very much
I tried install `mmh3` by using `pip`, the output like this:

```
Collecting mmh3
  Using cached https://files.pythonhosted.org/packages/fa/7e/3ddcab0a9fcea034212c02eb411433db9330e34d626360b97333368b4052/mmh3-2.5.1.tar.gz
Installing collected packages: mmh3
  Running setup.py install for mmh3 ... error
    Complete output from command d:\x64\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xiaowei\\AppData\\Local\\Temp\\pip-install-0mgunkhh\\mmh3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\xiaowei\AppData\Local\Temp\pip-record-55g0v33x\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'mmh3' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "d:\x64\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xiaowei\\AppData\\Local\\Temp\\pip-install-0mgunkhh\\mmh3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\xiaowei\AppData\Local\Temp\pip-record-55g0v33x\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\xiaowei\AppData\Local\Temp\pip-install-0mgunkhh\mmh3\
```
According the `https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat`,   looks like, i need install a `vs2015` for compile the code.  I will try late.

**Comment by kalafut** [comment]
It has been a while since I used Python on windows but that error does look familiar. At least if you fix it for this you’ll probably be fixing it for other future libraries as well.

**Comment by sharego** [comment]
After install the [Build Tools for Visual Studio 2017](https://visualstudio.microsoft.com/downloads/), now it can compile `mmh3`, and install `imohash` success, running good.  And find a pure python implement for 32-bit `mmh`: [pymmh3](https://github.com/wc-duck/pymmh3) 
Thanks a lot 👍

**Comment by kalafut** [comment]
Great!

**Comment by frennkie** [comment]
Would you consider removing `mmh3` from install requires on the PyPI package?

You could try to import it and if it fails use`pymmh3` as `mmh3` which is slower but does not require compilation (I ran into this issue on Windows).

**Comment by kalafut** [comment]
Thanks for the interest. This change would seem to put the onus on people to go and install `mmh3` or else suffer poor performance. The pymmh3 package seems much less mature than mmh3 which has large adoption, so that's another concern.

Is there perhaps a way provide a parameter during installation to opt in to a pymmh3 dependency instead? (I'm not sure... packaging was never a common thing for me and I've been away from this for a while.)

**Comment by frennkie** [comment]
I am also not a complete expert on the packaging issue. In the projects I have worked on I haven't seen the possibility for having switches when running pip install.

From my point of view everybody who today has py-imohash running already has the mmh3 installed. So dropping the dependency would not have an immediate bad effect on users.

For new installations I would update the install documentation to simply include mmh3. So in the readme.md it would then be `pip install imohash mmh3`.

For anybody who doesn't go there you could try to import mmh3 and fallback to py-mmh3 but immediately raise an `ImportWarning` Exception. User will get this and can conciously decide whether to catch and ignore this (having low performance) or actually install the real mmh3.

As far as I see it pymmh3 isn't even packaged.. So you would have to copy it into here make this approach work.

Let me know if you would consider this and I'll put some time into creating a PR.
