### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by amogorkon** [kalafut/py-imohash#8]
Hi,

I'd like to reuse your code, but you didn't specify any License?

Cheers!

**Comment by kalafut** [comment]
Whoops. Amazing I didn’t include that here. It’s MIT like its [parent project](https://github.com/kalafut/imohash). I did at least remember at https://pypi.org/project/imohash/#data. 

I’ll get that fixed here shortly. Thanks for noticing!

**Comment by amogorkon** [comment]
Thanks 👍
